### ISSUE TITLE
Телеграм

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [pandoraboxchain/whitepaper#1]
Приветствую. Интересный проект.
В видеодокладе в конце промелькнул слайд с чатом в телеграмме, но без адреса и ссылки.
Это ещё актуально? если да, то можете дать ссылку? или с таким вопросом лучше на мыло написать?

**Comment by 0x4E69676874466F78** [comment]
Нашёл канал @pandoraboxchain правда это не чат.

**Comment by dr-orlovsky** [comment]
Канал @pandoraboxchain — это не чат. Вопросы можно задавать в группе Telegram https://t.me/joinchat/EwMUjQ0fV8JbZn3kZhvtkA
